trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo Installing requirements
    pip install -r requirements.txt
  displayName: 'Install requirements'

- script: |
    echo Running short tests
    pytest tests/short
  displayName: 'Run short tests'
